### ISSUE TITLE
Entrevista 

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-8-entrevista-equipo-3#1]
[ENTREVISTA equipo 3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-entrevista-equipo-3/files/9942865/ENTREVISTA.equipo.3.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rubrica tiene 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
